"""Litchi LCHM binary mission exporter.

The LCHM binary layout implemented here was reverse-engineered from real
files generated by the Litchi app (see ``backend/tests/fixtures/litchi``).
This module serializes the 44-byte header, the 56-byte waypoint records, and
(optionally) the photo-capture trailer.

Fields that are present in real files but whose meaning has not been
confirmed (header padding bytes, record offset +4 and offset +36, the second
f32 of each trailer photo block) are written as documented structural
constants (``0``) and are labelled ``UNKNOWN``. The trailer layout
(altitude-mirror blocks, capture settings, per-waypoint photo distance,
trailing bytes) is confirmed against the fixtures and M1-M6/V1/V2 and is
documented in ``docs/export/litchi-lchm-trailer-analysis.md``. The trailer is
only emitted when ``options.photo_capture`` is provided (Litchi Export
Adapter).

All fields are big-endian (verified against the fixtures).
"""

from __future__ import annotations

import math
import re
import struct
from dataclasses import dataclass
from enum import IntEnum
from typing import Sequence

from .base import (
    CompatibilityCategory,
    CompatibilityInfo,
    ExportResult,
    ExportWarning,
    MissionExporter,
    ValidationError,
    ValidationResult,
    has_elevation_data,
    has_multiple_actions,
    has_terrain_following,
)
from .models import MissionExportData

LCHM_MAGIC = b"lchm"
LCHM_HEADER_SIZE = 44
LCHM_WAYPOINT_RECORD_SIZE = 56
LCHM_MAX_WAYPOINTS = 99

# Trailer layout (confirmed against real Litchi files M1-M6 / V1 / V2 and the
# 10-waypoint fixtures, see docs/export/litchi-lchm-trailer-analysis.md).
LCHM_TRAILER_LEADING_ZEROS = 6
LCHM_SECTION1_BLOCK_SIZE = 10
LCHM_TRAILER_SETTINGS_SIZE = 106
LCHM_TRAILER_TIMEINT_REL = 10
LCHM_TRAILER_PHOTO_BLOCK_SIZE = 8
LCHM_TRAILER_TAIL = b"\x00\x00\x00\x00\x09\x00"
LCHM_PHOTO_DIST_SENTINEL = -1.0

# 106-byte capture settings template, extracted from a real Litchi file with
# the photo_timeinterval slot (+10..+13) zeroed. Verified byte-identical (modulo
# the timeinterval slot) across the 10-waypoint fixtures and M1-M6/V1/V2.
_TRAILER_SETTINGS_TEMPLATE = bytes.fromhex(
    "005c000000080000000000000000000000000000000000000000000000000000"
    "0000c7c350000041f00000504600000000000000000000000000000000424800"
    "00000000023f8000000000000000000000000000000000000000000000000000"
    "00c7c350000000000000"
)


def lchm_settings_start(waypoint_count: int) -> int:
    """Offset (trailer-relative) where the 106-byte capture settings region begins.

    Scales with the waypoint count: ``6 + N * 10`` (verified for N=10 and
    N=65). Never a fixed absolute offset.
    """
    return LCHM_TRAILER_LEADING_ZEROS + waypoint_count * LCHM_SECTION1_BLOCK_SIZE


def lchm_photo_blocks_rel(waypoint_count: int) -> int:
    """Offset (trailer-relative) of the per-waypoint photo distance blocks.

    ``6 + N * 10 + 106``; N=10 gives 212, N=65 gives 762 (both verified).
    """
    return lchm_settings_start(waypoint_count) + LCHM_TRAILER_SETTINGS_SIZE


class LchmPhotoCaptureMode(IntEnum):
    NONE = 0
    TIME = 1
    DISTANCE = 2


class LchmPathMode(IntEnum):
    # byte[15] of the header (Fase 7 physical evidence):
    #   0x00 = STRAIGHT (recto), 0x01 = CURVED_TURNS (giros curvos)
    CURVED_TURNS = 0x01
    STRAIGHT = 0x00


class LchmHeadingMode(IntEnum):
    # byte[7] of the header (Fase 7 physical evidence):
    #   0x00 = FOLLOW_PATH (seguir camino), 0x03 = CUSTOM_POI (personalizado)
    CUSTOM_POI = 0x03
    FOLLOW_PATH = 0x00


class LchmFormatVersion(IntEnum):
    CURRENT = 1


class LchmError(Exception):
    """Base error for LCHM binary handling."""


class LchmFormatError(LchmError):
    """The file structure is not a valid LCHM."""


class LchmSerializationError(LchmError):
    """A value could not be serialized into the LCHM binary."""


class LchmValidationError(LchmError):
    """Serialized or parsed data failed semantic validation."""


class LchmUnsupportedConfigurationError(LchmError):
    """A requested mode/option is not supported by this LCHM version."""


class LchmWaypointError(LchmError):
    """A waypoint contains invalid data."""


class LchmBinaryWriter:
    """Big-endian binary writer with explicit, machine-independent methods."""

    def __init__(self) -> None:
        self._buf = bytearray()

    def write_bytes(self, data: bytes) -> None:
        self._buf.extend(data)

    def write_u8(self, value: int) -> None:
        self._buf.append(value & 0xFF)

    def write_i8(self, value: int) -> None:
        self._buf.extend(struct.pack(">b", value))

    def write_u16(self, value: int) -> None:
        self._buf.extend(struct.pack(">H", value))

    def write_i16(self, value: int) -> None:
        self._buf.extend(struct.pack(">h", value))

    def write_u32(self, value: int) -> None:
        self._buf.extend(struct.pack(">I", value))

    def write_i32(self, value: int) -> None:
        self._buf.extend(struct.pack(">i", value))

    def write_f32(self, value: float) -> None:
        self._buf.extend(struct.pack(">f", value))

    def write_f64(self, value: float) -> None:
        self._buf.extend(struct.pack(">d", value))

    def getvalue(self) -> bytes:
        return bytes(self._buf)


class LchmBinaryParser:
    """Big-endian reader over raw bytes; any external LCHM is untrusted."""

    def __init__(self, data: bytes) -> None:
        self._data = data
        self._offset = 0

    @property
    def offset(self) -> int:
        return self._offset

    @property
    def remaining(self) -> int:
        return len(self._data) - self._offset

    def _need(self, size: int) -> None:
        if self._offset + size > len(self._data):
            raise LchmFormatError(
                f"LCHM file truncated: needed {size} byte(s) at offset {self._offset}, only {self.remaining} remaining"
            )

    def read_bytes(self, size: int) -> bytes:
        self._need(size)
        chunk = self._data[self._offset : self._offset + size]
        self._offset += size
        return chunk

    def read_u8(self) -> int:
        return self.read_bytes(1)[0]

    def read_i8(self) -> int:
        return struct.unpack(">b", self.read_bytes(1))[0]

    def read_u16(self) -> int:
        return struct.unpack(">H", self.read_bytes(2))[0]

    def read_i16(self) -> int:
        return struct.unpack(">h", self.read_bytes(2))[0]

    def read_u32(self) -> int:
        return struct.unpack(">I", self.read_bytes(4))[0]

    def read_i32(self) -> int:
        return struct.unpack(">i", self.read_bytes(4))[0]

    def read_f32(self) -> float:
        return struct.unpack(">f", self.read_bytes(4))[0]

    def read_f64(self) -> float:
        return struct.unpack(">d", self.read_bytes(8))[0]


@dataclass
class LchmHeader:
    """Decoded LCHM header (known fields only)."""

    path_mode: LchmPathMode = LchmPathMode.STRAIGHT
    heading_mode: LchmHeadingMode = LchmHeadingMode.FOLLOW_PATH
    waypoint_count: int = 0
    raw: bytes = b""

    def to_bytes(self) -> bytes:
        return build_header(self.path_mode, self.heading_mode, self.waypoint_count)


@dataclass
class LchmWaypointRecord:
    """A single 56-byte LCHM waypoint record (known fields)."""

    latitude: float
    longitude: float
    altitude: float
    heading: float = 0.0
    speed: float = 0.0
    gimbal_mode: int = 2
    gimbal_pitch: int = -90
    flag: int = 0
    curve_radius_m: float = 0.0


@dataclass
class LchmPhotoCaptureOptions:
    """Litchi photo-capture configuration (TIME / DISTANCE / NONE).

    ``mode`` selects the capture style:
      * ``TIME``     — global ``photo_timeinterval`` (f32, seconds, > 0).
        ``distance_interval_m`` is optional and, when given, is written to the
        per-waypoint distance blocks (kept as-is, never derived from speed).
      * ``DISTANCE`` — per-waypoint ``photo_distinterval`` (f32, meters, >= 0).
        ``time_interval_s`` is forced to 0.
      * ``NONE``     — no photo capture; both fields are 0 / sentinel.

    This is the *Litchi* representation produced by the Litchi Export Adapter
    from the Universal mission (CaptureIntervalEngine's integer
    ``recommended_interval_s``). It is intentionally Litchi-specific; the
    universal engines are untouched.
    """

    mode: LchmPhotoCaptureMode = LchmPhotoCaptureMode.NONE
    time_interval_s: float | None = None
    distance_interval_m: float | None = None


def normalize_litchi_time_interval(interval_s: float | None) -> int | None:
    """Maps a recommended capture interval (seconds) to the integer Litchi value.

    Litchi stores ``photo_timeinterval`` as an integer number of seconds.
    The CaptureIntervalEngine's operational recommendation
    (``recommended_interval_s``) is already an integer; this function isolates
    the *rounding policy* so it can be reviewed independently (Phase 5 note:
    the floor vs round vs ceil decision is intentionally deferred until the
    engine policy and Map2Drone requirements are re-checked together).

    Conservative behaviour: never rounds *up* (a larger Litchi value would
    increase the actual photo spacing beyond what the engine guarantees), so a
    decimal recommendation such as 5.3 s maps to 5 s. ``None``/``<= 0`` map to
    ``None`` (no valid time interval).
    """
    if interval_s is None:
        return None
    value = float(interval_s)
    if not math.isfinite(value) or value <= 0:
        return None
    return int(math.floor(value))


@dataclass
class LchmParsedMission:
    path_mode: LchmPathMode
    heading_mode: LchmHeadingMode
    waypoints: list[LchmWaypointRecord]

    @property
    def waypoint_count(self) -> int:
        return len(self.waypoints)


class LchmHeaderWriter:
    """Builds the 44-byte header. Unknown bytes follow documented constants."""

    def write(self, path_mode: LchmPathMode, heading_mode: LchmHeadingMode, waypoint_count: int) -> bytes:
        return build_header(path_mode, heading_mode, waypoint_count)


class LchmHeaderParser:
    """Parses the 44-byte header, preserving unknown bytes."""

    def parse(self, data: bytes) -> LchmHeader:
        if len(data) < LCHM_HEADER_SIZE:
            raise LchmFormatError(f"LCHM header truncated: expected {LCHM_HEADER_SIZE} bytes, got {len(data)}")
        parser = LchmBinaryParser(data[:LCHM_HEADER_SIZE])
        magic = parser.read_bytes(4)
        if magic != LCHM_MAGIC:
            raise LchmFormatError(f"Invalid LCHM magic: {magic!r} (expected {LCHM_MAGIC!r})")
        parser.read_bytes(3)  # offset 4..6 (unknown/padding)
        heading_mode_byte = parser.read_u8()  # offset 7 (heading mode, Fase 7)
        parser.read_bytes(3)  # offset 8..10 (unknown/padding)
        parser.read_u8()  # offset 11 (constant 0x01)
        parser.read_bytes(3)  # offset 12..14 (unknown/padding)
        path_mode_byte = parser.read_u8()  # offset 15 (path mode, Fase 7)
        parser.read_f32()  # offset 16..19 (constant 8.0)
        parser.read_f32()  # offset 20..23 (constant 15.0)
        parser.read_u32()  # offset 24..27 (zeros)
        parser.read_u32()  # offset 28..31 (constant 0x00120000)
        parser.read_bytes(11)  # offset 32..42 (zeros)
        waypoint_count = parser.read_u8()
        return LchmHeader(
            path_mode=_path_mode_from_byte(path_mode_byte),
            heading_mode=_heading_mode_from_byte(heading_mode_byte),
            waypoint_count=waypoint_count,
            raw=bytes(data[:LCHM_HEADER_SIZE]),
        )


class LchmWaypointSerializer:
    """Serializes exactly ``LCHM_WAYPOINT_RECORD_SIZE`` bytes per waypoint."""

    def serialize_waypoint(self, wp: LchmWaypointRecord) -> bytes:
        writer = LchmBinaryWriter()
        writer.write_f32(wp.altitude)
        writer.write_i32(wp.flag)
        writer.write_f32(wp.heading)
        writer.write_f32(wp.speed)
        writer.write_i32(0)  # offset +16 (zeros)
        writer.write_f64(wp.latitude)
        writer.write_f64(wp.longitude)
        writer.write_f32(wp.curve_radius_m)
        writer.write_i32(int(round(wp.gimbal_mode)))
        writer.write_i32(int(round(wp.gimbal_pitch)))
        writer.write_i32(0)  # offset +48 (zeros)
        writer.write_i32(0)  # offset +52 (zeros)
        result = writer.getvalue()
        if len(result) != LCHM_WAYPOINT_RECORD_SIZE:
            raise LchmSerializationError(
                f"LCHM waypoint serialized to {len(result)} bytes, expected {LCHM_WAYPOINT_RECORD_SIZE}"
            )
        return result


class LchmTrailerSerializer:
    """Serializes the LCHM trailer (photo capture) region.

    Trailer layout (trailer-relative offsets, confirmed against real files
    M1-M6/V1/V2 and the 10-waypoint fixtures):

      * ``0 .. 5``: six zero bytes.
      * ``6 .. 6 + N*10``: one 10-byte altitude-mirror block per waypoint
        ``[alt f32 BE][0xFFFFFFFF][u16 0x0000]``.
      * ``settings_start .. settings_start + 106``: the 106-byte capture
        settings template (constant across files); ``photo_timeinterval`` is
        the f32 BE at ``settings_start + 10``.
      * ``settings_start + 106 .. +106 + N*8``: one 8-byte photo block per
        waypoint ``[photo_distinterval f32][other f32 UNKNOWN]``.
      * trailing: six bytes ``00 00 00 00 09 00``.

    Unknown bytes follow documented constants: the second f32 of each photo
    block is written as ``0.0`` (the most common value observed in real files)
    and is NOT given a semantic interpretation.
    """

    def serialize(
        self,
        waypoints: Sequence[LchmWaypointRecord],
        capture: LchmPhotoCaptureOptions | None = None,
    ) -> bytes:
        capture = capture or LchmPhotoCaptureOptions()
        n = len(waypoints)
        settings_start = lchm_settings_start(n)
        writer = LchmBinaryWriter()
        writer.write_bytes(b"\x00" * LCHM_TRAILER_LEADING_ZEROS)
        for wp in waypoints:
            writer.write_f32(wp.altitude)
            writer.write_bytes(b"\xff\xff\xff\xff")
            writer.write_u16(0)
        writer.write_bytes(self._build_settings(capture, settings_start))
        for wp in waypoints:
            dist = self._dist_for_waypoint(wp, capture)
            writer.write_f32(dist)
            writer.write_f32(0.0)  # UNKNOWN second f32 (documented constant)
        writer.write_bytes(LCHM_TRAILER_TAIL)
        return writer.getvalue()

    def _build_settings(self, capture: LchmPhotoCaptureOptions, settings_start: int) -> bytes:
        settings = bytearray(_TRAILER_SETTINGS_TEMPLATE)
        timeint = 0.0
        if capture.mode == LchmPhotoCaptureMode.TIME:
            timeint = float(normalize_litchi_time_interval(capture.time_interval_s) or 0.0)
        settings[LCHM_TRAILER_TIMEINT_REL : LCHM_TRAILER_TIMEINT_REL + 4] = struct.pack(">f", timeint)
        return bytes(settings)

    def _dist_for_waypoint(self, wp: LchmWaypointRecord, capture: LchmPhotoCaptureOptions) -> float:
        if capture.mode == LchmPhotoCaptureMode.DISTANCE:
            if capture.distance_interval_m is None or capture.distance_interval_m < 0:
                return LCHM_PHOTO_DIST_SENTINEL
            return capture.distance_interval_m
        if capture.mode == LchmPhotoCaptureMode.TIME and capture.distance_interval_m is not None:
            if capture.distance_interval_m < 0:
                return LCHM_PHOTO_DIST_SENTINEL
            return capture.distance_interval_m
        return LCHM_PHOTO_DIST_SENTINEL


class LchmValidator:
    """Validates serialized or parsed LCHM data against known constraints."""

    def validate_mission(
        self, waypoints: Sequence[LchmWaypointRecord], path_mode: LchmPathMode, heading_mode: LchmHeadingMode
    ) -> None:
        if path_mode not in (LchmPathMode.CURVED_TURNS, LchmPathMode.STRAIGHT):
            raise LchmValidationError(f"Unsupported LCHM path mode: {path_mode!r}")
        if heading_mode not in (LchmHeadingMode.CUSTOM_POI, LchmHeadingMode.FOLLOW_PATH):
            raise LchmValidationError(f"Unsupported LCHM heading mode: {heading_mode!r}")
        if len(waypoints) > LCHM_MAX_WAYPOINTS:
            raise LchmValidationError(
                f"LCHM supports at most {LCHM_MAX_WAYPOINTS} waypoints per mission (got {len(waypoints)})"
            )
        for i, wp in enumerate(waypoints):
            self._validate_waypoint(wp, i)

    def validate_photo_capture(self, capture: LchmPhotoCaptureOptions) -> None:
        """Validates Litchi photo-capture options before trailer serialization."""
        mode = capture.mode
        if mode == LchmPhotoCaptureMode.TIME:
            interval = normalize_litchi_time_interval(capture.time_interval_s)
            if interval is None:
                raise LchmValidationError(
                    f"LCHM TIME photo capture requires a positive time_interval_s (got {capture.time_interval_s!r})"
                )
            if capture.distance_interval_m is not None and capture.distance_interval_m < 0:
                raise LchmValidationError(
                    f"LCHM photo distance_interval_m cannot be negative (got {capture.distance_interval_m!r})"
                )
        elif mode == LchmPhotoCaptureMode.DISTANCE:
            if capture.distance_interval_m is None or capture.distance_interval_m < 0:
                raise LchmValidationError(
                    "LCHM DISTANCE photo capture requires a non-negative "
                    f"distance_interval_m (got {capture.distance_interval_m!r})"
                )
        elif mode != LchmPhotoCaptureMode.NONE:
            raise LchmValidationError(f"Unsupported LCHM photo capture mode: {mode!r}")

    def validate_bytes(self, data: bytes) -> LchmParsedMission:
        mission = parse_lchm(data)
        self.validate_mission(mission.waypoints, mission.path_mode, mission.heading_mode)
        return mission

    def _validate_waypoint(self, wp: LchmWaypointRecord, index: int) -> None:
        def _bad(field: str, reason: str) -> None:
            raise LchmValidationError(f"LCHM export failed: waypoint {index + 1} has invalid {field} ({reason}).")

        if not _is_finite(wp.latitude) or not (-90.0 <= wp.latitude <= 90.0):
            _bad("latitude", str(wp.latitude))
        if not _is_finite(wp.longitude) or not (-180.0 <= wp.longitude <= 180.0):
            _bad("longitude", str(wp.longitude))
        if not _is_finite(wp.altitude):
            _bad("altitude", str(wp.altitude))
        if not _is_finite(wp.speed) or wp.speed < 0:
            _bad("speed", str(wp.speed))
        if not _is_finite(wp.heading) or not (0.0 <= wp.heading < 360.0):
            _bad("heading", str(wp.heading))
        if not _is_finite(wp.gimbal_pitch):
            _bad("gimbal", str(wp.gimbal_pitch))


def build_header(path_mode: LchmPathMode, heading_mode: LchmHeadingMode, waypoint_count: int) -> bytes:
    return _build_header_clean(path_mode, heading_mode, waypoint_count)


def _build_header_clean(path_mode: LchmPathMode, heading_mode: LchmHeadingMode, waypoint_count: int) -> bytes:
    writer = LchmBinaryWriter()
    writer.write_bytes(LCHM_MAGIC)
    writer.write_bytes(b"\x00\x00\x00")  # offset 4..6
    writer.write_u8(int(heading_mode))  # offset 7 (heading mode, Fase 7)
    writer.write_bytes(b"\x00\x00\x00")  # offset 8..10
    writer.write_u8(0x01)  # offset 11
    writer.write_bytes(b"\x00\x00\x00")  # offset 12..14
    writer.write_u8(int(path_mode))  # offset 15 (path mode, Fase 7)
    writer.write_f32(8.0)  # offset 16..19
    writer.write_f32(15.0)  # offset 20..23
    writer.write_u32(0)  # offset 24..27
    writer.write_u32(0x00120000)  # offset 28..31
    writer.write_bytes(b"\x00" * 11)  # offset 32..42
    writer.write_u8(waypoint_count)  # offset 43
    return writer.getvalue()


def _path_mode_from_byte(value: int) -> LchmPathMode:
    for mode in (LchmPathMode.CURVED_TURNS, LchmPathMode.STRAIGHT):
        if int(mode) == value:
            return mode
    raise LchmFormatError(f"Unknown LCHM path mode byte: 0x{value:02x}")


def _heading_mode_from_byte(value: int) -> LchmHeadingMode:
    for mode in (LchmHeadingMode.CUSTOM_POI, LchmHeadingMode.FOLLOW_PATH):
        if int(mode) == value:
            return mode
    raise LchmFormatError(f"Unknown LCHM heading mode byte: 0x{value:02x}")


def _is_finite(value: float) -> bool:
    import math

    return isinstance(value, (int, float)) and math.isfinite(value)


def serialize_mission(
    waypoints: Sequence[LchmWaypointRecord], path_mode: LchmPathMode, heading_mode: LchmHeadingMode
) -> bytes:
    """Serializes header + waypoint records. No trailer is emitted."""
    writer = LchmBinaryWriter()
    writer.write_bytes(_build_header_clean(path_mode, heading_mode, len(waypoints)))
    serializer = LchmWaypointSerializer()
    for wp in waypoints:
        writer.write_bytes(serializer.serialize_waypoint(wp))
    return writer.getvalue()


def serialize_mission_with_photo_capture(
    waypoints: Sequence[LchmWaypointRecord],
    path_mode: LchmPathMode,
    heading_mode: LchmHeadingMode,
    capture: LchmPhotoCaptureOptions,
) -> bytes:
    """Serializes header + waypoint records + the photo-capture trailer."""
    base = serialize_mission(waypoints, path_mode, heading_mode)
    trailer = LchmTrailerSerializer().serialize(waypoints, capture)
    return base + trailer


def parse_lchm(data: bytes) -> LchmParsedMission:
    """Parses an LCHM file. Any external file is treated as untrusted."""
    header = LchmHeaderParser().parse(data)
    if len(data) < LCHM_HEADER_SIZE + header.waypoint_count * LCHM_WAYPOINT_RECORD_SIZE:
        raise LchmFormatError(
            f"LCHM file truncated: header claims {header.waypoint_count} waypoint(s) of "
            f"{LCHM_WAYPOINT_RECORD_SIZE} bytes each but the file is too short"
        )
    parser = LchmBinaryParser(data)
    parser.read_bytes(LCHM_HEADER_SIZE)
    waypoints: list[LchmWaypointRecord] = []
    for _ in range(header.waypoint_count):
        record_bytes = parser.read_bytes(LCHM_WAYPOINT_RECORD_SIZE)
        rec_parser = LchmBinaryParser(record_bytes)
        altitude = rec_parser.read_f32()
        flag = rec_parser.read_i32()
        heading = rec_parser.read_f32()
        speed = rec_parser.read_f32()
        rec_parser.read_i32()  # offset +16 (zeros)
        latitude = rec_parser.read_f64()
        longitude = rec_parser.read_f64()
        unknown_f32 = rec_parser.read_f32()
        gimbal_mode = rec_parser.read_i32()
        gimbal_pitch = rec_parser.read_i32()
        rec_parser.read_i32()  # offset +48 (zeros)
        rec_parser.read_i32()  # offset +52 (zeros)
        waypoints.append(
            LchmWaypointRecord(
                latitude=latitude,
                longitude=longitude,
                altitude=altitude,
                heading=heading,
                speed=speed,
                gimbal_mode=gimbal_mode,
                gimbal_pitch=gimbal_pitch,
                flag=flag,
                curve_radius_m=unknown_f32,
            )
        )
    return LchmParsedMission(header.path_mode, header.heading_mode, waypoints)


def lchm_diff(file_a: bytes, file_b: bytes) -> str:
    """Dev utility: reports grouped byte differences between two LCHM files."""
    changes: list[tuple[int, int, int]] = []
    length = max(len(file_a), len(file_b))
    for i in range(length):
        old_byte = file_a[i] if i < len(file_a) else None
        new_byte = file_b[i] if i < len(file_b) else None
        if old_byte != new_byte:
            changes.append((i, old_byte, new_byte))
    if not changes:
        return "No differences."
    lines: list[str] = []
    run: list[tuple[int, int, int]] = []
    for change in changes:
        if run and change[0] != run[-1][0] + 1:
            lines.extend(_diff_lines_for_run(run))
            run = []
        run.append(change)
    lines.extend(_diff_lines_for_run(run))
    return "\n".join(lines)


def _trailer_start(data: bytes) -> int:
    """Offset where the trailer begins (after header + waypoint records)."""
    mission = parse_lchm(data)
    return LCHM_HEADER_SIZE + mission.waypoint_count * LCHM_WAYPOINT_RECORD_SIZE


def lchm_trailer_diff(files: dict[str, bytes]) -> str:
    """Dev utility: grouped trailer comparison across multiple LCHM files.

    ``files`` maps a label (e.g. "A", "B", "C") to raw file bytes. Reports
    absolute offsets, trailer-relative offsets, per-file bytes, run grouping,
    constant bytes and suspected block boundaries.
    """
    labels = list(files.keys())
    if len(labels) < 2:
        raise ValueError("lchm_trailer_diff requires at least two files")
    starts = {label: _trailer_start(data) for label, data in files.items()}
    lengths = {label: len(data) - starts[label] for label, data in files.items()}
    trailer_length = max(lengths.values())

    out: list[str] = []
    out.append("TRAILER ANALYSIS")
    out.append(f"labels: {', '.join(labels)}")
    for label in labels:
        out.append(f"  {label}: total={len(files[label])}B start={starts[label]} trailer={lengths[label]}B")
    out.append("")

    # Constant bytes across all files.
    constant: list[int] = []
    variable: list[int] = []
    for rel in range(trailer_length):
        values = [files[label][starts[label] + rel] for label in labels if rel < lengths[label]]
        if not values:
            continue
        if all(v == values[0] for v in values):
            constant.append(rel)
        else:
            variable.append(rel)

    out.append(f"Constant trailer bytes (relative): {len(constant)} of {trailer_length}")
    out.append(f"Variable trailer bytes (relative): {len(variable)} of {trailer_length}")
    out.append("")

    # Show variable runs with all file byte values.
    out.append("VARIABLE REGIONS (trailer-relative, hex):")
    for label in labels:
        rel_start = starts[label]
        out.append(f"  {label}: " + " ".join(f"{b:02x}" for b in files[label][rel_start:]))
    out.append("")

    # Grouped changes, aligned to the shortest trailer.
    min_len = min(lengths.values())
    out.append("GROUPED DIFFERENCES (relative offsets, all files):")
    rel = 0
    while rel < min_len:
        ref = files[labels[0]][starts[labels[0]] + rel]
        row = [ref]
        differs = False
        for label in labels[1:]:
            b = files[label][starts[label] + rel]
            row.append(b)
            if b != ref:
                differs = True
        if differs:
            run_end = rel
            while run_end + 1 < min_len:
                nxt_ref = files[labels[0]][starts[labels[0]] + run_end + 1]
                nxt_row = [files[label][starts[label] + run_end + 1] for label in labels]
                if nxt_row[0] != nxt_ref or any(v != nxt_row[0] for v in nxt_row[1:]):
                    break
                run_end += 1
            hex_row = " ".join(f"{v:02x}" for v in row)
            base = starts[labels[0]]
            out.append(
                f"  rel {rel:3d}-{run_end:3d}  abs {base + rel:4d}-{base + run_end:4d}  [{', '.join(labels)}] {hex_row}"
            )
            rel = run_end + 1
        else:
            rel += 1
    out.append("")

    # Constant block summaries.
    out.append("CONSTANT RUNS (trailer-relative):")
    rel = 0
    while rel < trailer_length:
        if rel in constant:
            run_end = rel
            while run_end + 1 < trailer_length and run_end + 1 in constant:
                run_end += 1
            out.append(f"  rel {rel:3d}-{run_end:3d}  ({run_end - rel + 1} bytes constant)")
            rel = run_end + 1
        else:
            rel += 1
    return "\n".join(out)


def _diff_lines_for_run(run: list[tuple[int, int, int]]) -> list[str]:
    old_bytes = "".join("??" if b is None else f"{b:02x}" for _, b, _ in run)
    new_bytes = "".join("??" if b is None else f"{b:02x}" for _, _, b in run)
    if len(run) == 1:
        offset, old_b, new_b = run[0]
        old_str = "??" if old_b is None else f"{old_b:02x}"
        new_str = "??" if new_b is None else f"{new_b:02x}"
        return [f"offset {offset}: {old_str} → {new_str}"]
    start = run[0][0]
    end = run[-1][0]
    return [f"offset {start}-{end}: {old_bytes} → {new_bytes}"]


# Trailer per-waypoint photo pair region (confirmed against fixture A's CSV:
# the first f32 of each 8-byte block equals photo_distinterval for that waypoint).
LCHM_TRAILER_PHOTO_BLOCK_REL = lchm_photo_blocks_rel(10)  # backward-compat constant (N=10)
LCHM_TRAILER_PHOTO_BLOCK_SIZE = 8


def lchm_trailer_photo_blocks(data: bytes) -> list[tuple[float, float]]:
    """Read-only: returns the per-waypoint [f32, f32] photo pairs from the trailer.

    Only meaningful for real Litchi files that contain a trailer; exported
    missions without photo capture carry no trailer, so this returns an empty
    list for those. The region scales with the waypoint count
    (``6 + N*10 + 106``); the interpretation is documented in
    ``docs/export/litchi-lchm-trailer-analysis.md`` (photo_distinterval CONFIRMED
    10/10 vs CSV; the second f32 is UNKNOWN).
    """
    trailer_start = _trailer_start(data)
    trailer = data[trailer_start:]
    mission = parse_lchm(data)
    n_wp = mission.waypoint_count
    need = lchm_photo_blocks_rel(n_wp) + n_wp * LCHM_TRAILER_PHOTO_BLOCK_SIZE
    if len(trailer) < need:
        return []
    blocks: list[tuple[float, float]] = []
    for i in range(n_wp):
        off = lchm_photo_blocks_rel(n_wp) + i * LCHM_TRAILER_PHOTO_BLOCK_SIZE
        a = struct.unpack(">f", trailer[off : off + 4])[0]
        b = struct.unpack(">f", trailer[off + 4 : off + 8])[0]
        blocks.append((a, b))
    return blocks


def sanitize_filename(name: str) -> str:
    """Sanitizes a mission name for safe file naming (lowercase, underscored)."""
    cleaned = re.sub(r"[^A-Za-z0-9_.\-]", "_", name.strip())
    cleaned = re.sub(r"[\s_]+", "_", cleaned)
    cleaned = cleaned.strip("._").lower()
    return cleaned or "mission"


class LchmExporter(MissionExporter):
    name = "Litchi LCHM"
    extension = ".lchm"
    version = "1.0"
    description = "Misión binaria Litchi (.lchm) generada por ingeniería inversa"
    compatibility = CompatibilityInfo(
        category=CompatibilityCategory.REVERSE_ENGINEERED,
        description=(
            "LCHM compatibility verified against supplied Litchi-generated fixtures and the "
            "currently implemented LCHM structure. No se garantiza compatibilidad total con "
            "todas las versiones de Litchi; comprobar la importación antes de volar."
        ),
    )

    def validate(self, mission: MissionExportData) -> ValidationResult:
        errors: list[ValidationError] = []
        if not mission.waypoints:
            errors.append(
                ValidationError(
                    field="waypoints",
                    message="LCHM export requires at least one waypoint",
                )
            )
        if len(mission.waypoints) > LCHM_MAX_WAYPOINTS:
            errors.append(
                ValidationError(
                    field="waypoints",
                    message=(
                        f"Litchi LCHM soporta máximo {LCHM_MAX_WAYPOINTS} waypoints por misión "
                        f"(se tienen {len(mission.waypoints)})"
                    ),
                )
            )
        for i, wp in enumerate(mission.waypoints):
            if not (isinstance(wp.latitude, (int, float)) and -90.0 <= wp.latitude <= 90.0):
                errors.append(ValidationError(field="waypoints", message=f"waypoint {i + 1}: latitude inválida"))
            if not (isinstance(wp.longitude, (int, float)) and -180.0 <= wp.longitude <= 180.0):
                errors.append(ValidationError(field="waypoints", message=f"waypoint {i + 1}: longitude inválida"))
        return ValidationResult(valid=len(errors) == 0, errors=errors)

    def get_warnings(self, mission: MissionExportData) -> list[ExportWarning]:
        warnings: list[ExportWarning] = []
        if has_elevation_data(mission):
            warnings.append(
                ExportWarning(
                    code="elevation_lost",
                    message=(
                        "LCHM no representa la elevación del terreno (MSL/AGL); las alturas se "
                        "exportan como valores finales del modelo."
                    ),
                    fields=["elevation_msnm", "agl"],
                )
            )
        if has_terrain_following(mission):
            warnings.append(
                ExportWarning(
                    code="terrain_following_lost",
                    message="LCHM no soporta seguimiento de terreno; se exportan alturas fijas.",
                    fields=["terrain_following"],
                )
            )
        if has_multiple_actions(mission):
            warnings.append(
                ExportWarning(
                    code="actions_lost",
                    message="Las acciones de cámara/gimbal por waypoint no se serializan en LCHM en esta versión.",
                    fields=["actions"],
                )
            )
        if mission.capture_interval_s and not self._has_photo_capture(mission):
            warnings.append(
                ExportWarning(
                    code="photo_interval_not_serialized",
                    message=(
                        "El intervalo de captura recomendado se calcula por separado y no se "
                        "incorpora todavía al archivo LCHM."
                    ),
                    fields=["capture_interval_s"],
                )
            )
        return warnings

    def _has_photo_capture(self, mission: MissionExportData) -> bool:
        options = mission.options or {}
        return options.get("photo_capture") is not None

    def export(self, mission: MissionExportData) -> ExportResult:
        options = mission.options or {}
        path_mode = _resolve_path_mode(options.get("path_mode"))
        heading_mode = _resolve_heading_mode(options.get("heading_mode"))
        capture = _resolve_photo_capture(options.get("photo_capture"))
        if capture is not None:
            LchmValidator().validate_photo_capture(capture)
        total = len(mission.waypoints)
        waypoints = [
            LchmWaypointRecord(
                latitude=wp.latitude,
                longitude=wp.longitude,
                altitude=wp.altitude,
                heading=_normalize_heading(wp.heading),
                speed=(float(wp.speed) if wp.speed is not None and wp.speed > 0 else mission.speed_ms),
                gimbal_mode=wp.gimbal_mode,
                gimbal_pitch=wp.gimbal_pitch,
                curve_radius_m=(float(wp.curve_size) if wp.curve_size and wp.curve_size > 0 else 0.0),
            )
            for wp in mission.waypoints
        ]
        # Match Litchi's curved-turn encoding observed in the user's physical
        # file (area_grid_74_time5_curve.lchm, Fase 7b):
        #   * turn radius (+36) is 0.0 on the first and last waypoint, and the
        #     curve size on every interior waypoint (they have no turn);
        #   * the +7 turn flag alternates 0/1 (odd waypoints = 1).
        if path_mode is LchmPathMode.CURVED_TURNS and total > 2:
            for i in range(total):
                if i in (0, total - 1):
                    waypoints[i].curve_radius_m = 0.0
                elif i % 2 == 1:
                    waypoints[i].flag = 0x01
        # Hard guard (Fase 10C-13): refuse to serialize missions over the LCHM
        # capacity. The header stores the waypoint count in a u8 (offset 43) and
        # Litchi itself caps at 99 waypoints; exporting more would silently wrap
        # the count and produce a corrupt file. The binary layout is untouched.
        LchmValidator().validate_mission(waypoints, path_mode, heading_mode)
        if capture is not None:
            data = serialize_mission_with_photo_capture(waypoints, path_mode, heading_mode, capture)
        else:
            data = serialize_mission(waypoints, path_mode, heading_mode)
        LchmValidator().validate_bytes(data)
        filename = f"{sanitize_filename(mission.project_name)}_litchi.lchm"
        return ExportResult(
            data=data,
            filename=filename,
            mime_type="application/octet-stream",
            is_binary=True,
        )


def _normalize_heading(heading: float) -> float:
    value = float(heading)
    value = value % 360.0
    return value


def _resolve_photo_capture(value: object) -> LchmPhotoCaptureOptions | None:
    """Litchi Export Adapter: maps the exporter ``photo_capture`` option to
    :class:`LchmPhotoCaptureOptions`.

    Accepts ``None`` (no photo capture), an existing
    :class:`LchmPhotoCaptureOptions`, or a dict with ``mode``
    (``NONE``/``TIME``/``DISTANCE``), ``time_interval_s`` and
    ``distance_interval_m``. The dict form is what the API/frontend send; the
    recommended interval from the Universal mission is normalized through
    :func:`normalize_litchi_time_interval`.
    """
    if value is None:
        return None
    if isinstance(value, LchmPhotoCaptureOptions):
        return value
    if not isinstance(value, dict):
        raise LchmUnsupportedConfigurationError(
            f"Unsupported LCHM photo_capture: {value!r} (expected a dict or LchmPhotoCaptureOptions)"
        )
    mode_value = value.get("mode", "NONE")
    if isinstance(mode_value, LchmPhotoCaptureMode):
        mode = mode_value
    else:
        name = str(mode_value).upper()
        if name in ("NONE", "NO", "OFF"):
            mode = LchmPhotoCaptureMode.NONE
        elif name in ("TIME", "TIMER", "INTERVAL"):
            mode = LchmPhotoCaptureMode.TIME
        elif name in ("DISTANCE", "DIST", "SPACING"):
            mode = LchmPhotoCaptureMode.DISTANCE
        else:
            raise LchmUnsupportedConfigurationError(
                f"Unsupported LCHM photo_capture.mode: {mode_value!r} (expected NONE, TIME or DISTANCE)"
            )
    time_interval_s = value.get("time_interval_s")
    distance_interval_m = value.get("distance_interval_m")
    return LchmPhotoCaptureOptions(
        mode=mode,
        time_interval_s=float(time_interval_s) if time_interval_s is not None else None,
        distance_interval_m=float(distance_interval_m) if distance_interval_m is not None else None,
    )


def _resolve_path_mode(value: object) -> LchmPathMode:
    if value is None:
        return LchmPathMode.STRAIGHT
    if isinstance(value, LchmPathMode):
        return value
    name = str(value).upper()
    if name in ("STRAIGHT", "RECT"):
        return LchmPathMode.STRAIGHT
    if name in ("CURVED_TURNS", "CURVED", "CURVO"):
        return LchmPathMode.CURVED_TURNS
    raise LchmUnsupportedConfigurationError(
        f"Unsupported LCHM path_mode: {value!r} (expected STRAIGHT or CURVED_TURNS)"
    )


def _resolve_heading_mode(value: object) -> LchmHeadingMode:
    if value is None:
        return LchmHeadingMode.FOLLOW_PATH
    if isinstance(value, LchmHeadingMode):
        return value
    name = str(value).upper()
    if name in ("FOLLOW_PATH", "FOLLOW"):
        return LchmHeadingMode.FOLLOW_PATH
    if name in ("CUSTOM_POI", "CUSTOM", "POI"):
        return LchmHeadingMode.CUSTOM_POI
    raise LchmUnsupportedConfigurationError(
        f"Unsupported LCHM heading_mode: {value!r} (expected FOLLOW_PATH or CUSTOM_POI)"
    )
